#!/bin/bash
# startup script starts all the services on the container required to
# run the lab 

# Usage of the Script 

# To use startup.sh, run the command
# ./scripts/startup.sh

# starts the Nginx service
service nginx start

